<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \AppBundle\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'nompersonne', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'prenompersonne', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'genre', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'personneAbonnement', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'voyage'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'nompersonne', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'prenompersonne', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'genre', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'personneAbonnement', '' . "\0" . 'AppBundle\\Entity\\Personne' . "\0" . 'voyage'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNompersonne($nompersonne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNompersonne', [$nompersonne]);

        return parent::setNompersonne($nompersonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getNompersonne()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getNompersonne();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNompersonne', []);

        return parent::getNompersonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenompersonne($prenompersonne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenompersonne', [$prenompersonne]);

        return parent::setPrenompersonne($prenompersonne);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenompersonne()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getPrenompersonne();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenompersonne', []);

        return parent::getPrenompersonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonneAbonnement(\AppBundle\Entity\Abonnement $personneAbonnement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonneAbonnement', [$personneAbonnement]);

        return parent::setPersonneAbonnement($personneAbonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonneAbonnement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonneAbonnement', []);

        return parent::getPersonneAbonnement();
    }

    /**
     * {@inheritDoc}
     */
    public function addVoyage(\AppBundle\Entity\Lieu $voyage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVoyage', [$voyage]);

        return parent::addVoyage($voyage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVoyage(\AppBundle\Entity\Lieu $voyage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVoyage', [$voyage]);

        return parent::removeVoyage($voyage);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoyage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoyage', []);

        return parent::getVoyage();
    }

}
